/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.sohu.saccount.thrift;

import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;
import org.apache.thrift.scheme.TupleScheme;

import java.util.*;

public class TestModel implements org.apache.thrift.TBase<TestModel, TestModel._Fields>, java.io.Serializable, Cloneable {
    private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("TestModel");

    private static final org.apache.thrift.protocol.TField PAYLOAD_FIELD_DESC = new org.apache.thrift.protocol.TField("payload", org.apache.thrift.protocol.TType.STRING, (short) 1);

    private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();

    static {
        schemes.put(StandardScheme.class, new TestModelStandardSchemeFactory());
        schemes.put(TupleScheme.class, new TestModelTupleSchemeFactory());
    }

    public String payload; // required

    /**
     * The set of fields this struct contains, along with convenience methods for finding and manipulating them.
     */
    public enum _Fields implements org.apache.thrift.TFieldIdEnum {
        PAYLOAD((short) 1, "payload");

        private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

        static {
            for (_Fields field : EnumSet.allOf(_Fields.class)) {
                byName.put(field.getFieldName(), field);
            }
        }

        /**
         * Find the _Fields constant that matches fieldId, or null if its not found.
         */
        public static _Fields findByThriftId(int fieldId) {
            switch (fieldId) {
                case 1: // PAYLOAD
                    return PAYLOAD;
                default:
                    return null;
            }
        }

        /**
         * Find the _Fields constant that matches fieldId, throwing an exception
         * if it is not found.
         */
        public static _Fields findByThriftIdOrThrow(int fieldId) {
            _Fields fields = findByThriftId(fieldId);
            if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
            return fields;
        }

        /**
         * Find the _Fields constant that matches name, or null if its not found.
         */
        public static _Fields findByName(String name) {
            return byName.get(name);
        }

        private final short _thriftId;
        private final String _fieldName;

        _Fields(short thriftId, String fieldName) {
            _thriftId = thriftId;
            _fieldName = fieldName;
        }

        public short getThriftFieldId() {
            return _thriftId;
        }

        public String getFieldName() {
            return _fieldName;
        }
    }

    // isset id assignments
    public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;

    static {
        Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
        tmpMap.put(_Fields.PAYLOAD, new org.apache.thrift.meta_data.FieldMetaData("payload", org.apache.thrift.TFieldRequirementType.DEFAULT,
                new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
        metaDataMap = Collections.unmodifiableMap(tmpMap);
        org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(TestModel.class, metaDataMap);
    }

    public TestModel() {
    }

    public TestModel(
            String payload) {
        this();
        this.payload = payload;
    }

    /**
     * Performs a deep copy on <i>other</i>.
     */
    public TestModel(TestModel other) {
        if (other.isSetPayload()) {
            this.payload = other.payload;
        }
    }

    public TestModel deepCopy() {
        return new TestModel(this);
    }

    @Override
    public void clear() {
        this.payload = null;
    }

    public String getPayload() {
        return this.payload;
    }

    public TestModel setPayload(String payload) {
        this.payload = payload;
        return this;
    }

    public void unsetPayload() {
        this.payload = null;
    }

    /**
     * Returns true if field payload is set (has been assigned a value) and false otherwise
     */
    public boolean isSetPayload() {
        return this.payload != null;
    }

    public void setPayloadIsSet(boolean value) {
        if (!value) {
            this.payload = null;
        }
    }

    public void setFieldValue(_Fields field, Object value) {
        switch (field) {
            case PAYLOAD:
                if (value == null) {
                    unsetPayload();
                } else {
                    setPayload((String) value);
                }
                break;

        }
    }

    public Object getFieldValue(_Fields field) {
        switch (field) {
            case PAYLOAD:
                return getPayload();

        }
        throw new IllegalStateException();
    }

    /**
     * Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise
     */
    public boolean isSet(_Fields field) {
        if (field == null) {
            throw new IllegalArgumentException();
        }

        switch (field) {
            case PAYLOAD:
                return isSetPayload();
        }
        throw new IllegalStateException();
    }

    @Override
    public boolean equals(Object that) {
        if (that == null)
            return false;
        if (that instanceof TestModel)
            return this.equals((TestModel) that);
        return false;
    }

    public boolean equals(TestModel that) {
        if (that == null)
            return false;

        boolean this_present_payload = true && this.isSetPayload();
        boolean that_present_payload = true && that.isSetPayload();
        if (this_present_payload || that_present_payload) {
            if (!(this_present_payload && that_present_payload))
                return false;
            if (!this.payload.equals(that.payload))
                return false;
        }

        return true;
    }

    @Override
    public int hashCode() {
        return 0;
    }

    public int compareTo(TestModel other) {
        if (!getClass().equals(other.getClass())) {
            return getClass().getName().compareTo(other.getClass().getName());
        }

        int lastComparison = 0;
        TestModel typedOther = (TestModel) other;

        lastComparison = Boolean.valueOf(isSetPayload()).compareTo(typedOther.isSetPayload());
        if (lastComparison != 0) {
            return lastComparison;
        }
        if (isSetPayload()) {
            lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.payload, typedOther.payload);
            if (lastComparison != 0) {
                return lastComparison;
            }
        }
        return 0;
    }

    public _Fields fieldForId(int fieldId) {
        return _Fields.findByThriftId(fieldId);
    }

    public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
        schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
        schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TestModel(");
        boolean first = true;

        sb.append("payload:");
        if (this.payload == null) {
            sb.append("null");
        } else {
            sb.append(this.payload);
        }
        first = false;
        sb.append(")");
        return sb.toString();
    }

    public void validate() throws org.apache.thrift.TException {
        // check for required fields
        // check for sub-struct validity
    }

    private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
        try {
            write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
        } catch (org.apache.thrift.TException te) {
            throw new java.io.IOException(te);
        }
    }

    private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
        try {
            read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
        } catch (org.apache.thrift.TException te) {
            throw new java.io.IOException(te);
        }
    }

    private static class TestModelStandardSchemeFactory implements SchemeFactory {
        public TestModelStandardScheme getScheme() {
            return new TestModelStandardScheme();
        }
    }

    private static class TestModelStandardScheme extends StandardScheme<TestModel> {

        public void read(org.apache.thrift.protocol.TProtocol iprot, TestModel struct) throws org.apache.thrift.TException {
            org.apache.thrift.protocol.TField schemeField;
            iprot.readStructBegin();
            while (true) {
                schemeField = iprot.readFieldBegin();
                if (schemeField.type == org.apache.thrift.protocol.TType.STOP) {
                    break;
                }
                switch (schemeField.id) {
                    case 1: // PAYLOAD
                        if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
                            struct.payload = iprot.readString();
                            struct.setPayloadIsSet(true);
                        } else {
                            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
                        }
                        break;
                    default:
                        org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
                }
                iprot.readFieldEnd();
            }
            iprot.readStructEnd();

            // check for required fields of primitive type, which can't be checked in the validate method
            struct.validate();
        }

        public void write(org.apache.thrift.protocol.TProtocol oprot, TestModel struct) throws org.apache.thrift.TException {
            struct.validate();

            oprot.writeStructBegin(STRUCT_DESC);
            if (struct.payload != null) {
                oprot.writeFieldBegin(PAYLOAD_FIELD_DESC);
                oprot.writeString(struct.payload);
                oprot.writeFieldEnd();
            }
            oprot.writeFieldStop();
            oprot.writeStructEnd();
        }

    }

    private static class TestModelTupleSchemeFactory implements SchemeFactory {
        public TestModelTupleScheme getScheme() {
            return new TestModelTupleScheme();
        }
    }

    private static class TestModelTupleScheme extends TupleScheme<TestModel> {

        @Override
        public void write(org.apache.thrift.protocol.TProtocol prot, TestModel struct) throws org.apache.thrift.TException {
            TTupleProtocol oprot = (TTupleProtocol) prot;
            BitSet optionals = new BitSet();
            if (struct.isSetPayload()) {
                optionals.set(0);
            }
            oprot.writeBitSet(optionals, 1);
            if (struct.isSetPayload()) {
                oprot.writeString(struct.payload);
            }
        }

        @Override
        public void read(org.apache.thrift.protocol.TProtocol prot, TestModel struct) throws org.apache.thrift.TException {
            TTupleProtocol iprot = (TTupleProtocol) prot;
            BitSet incoming = iprot.readBitSet(1);
            if (incoming.get(0)) {
                struct.payload = iprot.readString();
                struct.setPayloadIsSet(true);
            }
        }
    }

}

